tasks:
    runEchoCommand:
        name: Runs pwd command
        triggeredBy:
            - postDevcontainerStart
        command: echo '[MAIN] Container working_dir:' >> /workspaces/container.log && pwd >> /workspaces/container.log
